POST http://localhost:4002/products
content-type: application/json

{
    "name": "Lapis",
    "price": 1.40
}

###Enviar

GET http://localhost:4002/products

###--------------------------------

###Buscar - Colocar após a ultima / 

GET http://localhost:4002/products/

###--------------------------------

###Alterar

PUT http://localhost:4002/products/
content-type: application/json

{
    "name": "Lapis",
    "price": 1.40
}

###---------------------------------

### Remover

DELETE http://localhost:4002/products/c4ffee5-489e-423b-bbe5-35c61f8e9fb6

###---------------------------------